version: 0.2

phases:

  pre_build:
    commands:
      - echo "Perform sast here!"
      - docker run --rm -e "WORKSPACE=${PWD}" -v ~/.m2:/.m2 -v $PWD:/app shiftleft/scan scan --src /app --type java
      - npm install snyk-to-html -g
